CREATE TABLE [dbo].[tCustomer]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY, 
	[AccountId] UNIQUEIDENTIFIER NOT NULL,
	[Email] NVARCHAR(100) NOT NULL,
    [Firstname] NVARCHAR(50) NOT NULL, 
    [Lastname] NVARCHAR(100) NOT NULL
)
